### ISSUE TITLE
Enable People to store all Organisation Data

### ISSUE THREAD

**Issue by mihaibivol** [rosedu/rosedu-people#105]
## Need

``` gherkin
In order to make People a reliable information source
As a ROSEdu stalker
I want to see accurate information about projects and people
```
## TODOs
- [ ] Add unnactivated accounts for everyone that ever participated in an activity #106
- [ ] Add request account form 
- [ ] Display only activated accounts
- [ ] Make the app accessible without login
## Future Development
- [ ] Add Social Auth
