### ISSUE TITLE
Add unactivated accounts

### ISSUE THREAD

**Issue by mihaibivol** [rosedu/rosedu-people#106]
Parent issue #105 
## Deliverables
- [ ] Management command to add phony accounts (accounts with no email)
- [ ] Management command to invite people to use the application

``` gherkin
Scenario: Add phony accounts
  Given I am logged in on the deployed application server
  And I have the <file> with the columns First Name, Last Name, User Name, Email
  When I run ./manage.py add_accounts <file>
  Then for each row in <file> having <First Name> <Last Name> <User Name> <Email>
  I will see in admin an Account with <First Name> <Last Name> <Username> an unusable password and empty email
  Examples:
    | file   | First Name | Last Name  | User Name | Email              |
    | in.txt | Gigi       | Duru       | gigi.duru | gigi.duru@duru.com |
    | in.txt | Ion        | Glanetasul | ion.gl    | ion@glie.com       |

Scenario: Invite accounts
  Given I am logged in on the deployed application server
  And I have the <file> with the columns First Name, Last Name, User Name, Email
  When I run ./manage.py invite_accounts <file>
  Then for each row in <file> having <First Name> <Last Name> <User Name> <Email>
  A random password will be generated for <User Name>
  And an email will be sent at <Email> containing <User Name> and the generated password.
  Examples:
    | file   | First Name | Last Name  | User Name | Email              |
    | in.txt | Gigi       | Duru       | gigi.duru | gigi.duru@duru.com |
    | in.txt | Ion        | Glanetasul | ion.gl    | ion@glie.com       |
```
## Solution
- [ ] Add management commands replacing existing invite_users command
## TODOs
- [ ] Add management commands
- [ ] Document them in the repository
  #### Prerequisites
  - Django Management Commands
#### Files
- rppl/people/management/*
