### ISSUE TITLE
Passing Test Suite

### ISSUE THREAD

**Issue by mihaibivol** [rosedu/rosedu-people#71]
## Need

``` gherkin
In order to check I don't introduce bugs
As a developer
I want a stable test suite
```
## Deliverables
- [x] Passing test suite when running ./manage.py test
- [ ] Code coverage in tests for all models and views
#### Abstract

In order to achieve a good test suite we need to do the following:
- [ ] Fix the current failing tests
- [ ] Add tests for all models and views
#### Prerequisites

https://docs.djangoproject.com/en/1.0/topics/testing/
http://www.realpython.com/blog/python/testing-in-django-part-1-best-practices-and-examples/#.UlFRMpwW2bU
#### TODO
- [ ] Fix django.contrib.auth failing test. Currently we use the default django.contrib.auth default login view with another template and url. This makes the test fail. A solution might be [this one](http://stackoverflow.com/questions/5480608/monkey-patched-django-auths-login-now-its-tests-fail)
- [x] Create a tests module for the people app
- [ ] Add unit tests for models
- [ ] Add unit tests for views
- [ ] Add unit tests for forms
